# Generated by Django 6.0.4 on 2026-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_outfitlyuser_login_outfitlyuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfitlyuser',
            name='username',
        ),
        migrations.AddField(
            model_name='outfitlyuser',
            name='login',
            field=models.CharField(default='user', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
