# Generated by Django 6.0.4 on 2026-04-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_outfitlyuser_username_outfitlyuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
    ]
