# Generated by Django 6.0.4 on 2026-05-27 14:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
