# Generated by Django 6.0.4 on 2026-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_cloth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
