# Generated by Django 6.0.4 on 2026-05-31 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_cloth_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 31, 13, 30, 26, 449009, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
